/**
 * Stealth Evasion Module for WebView
 * 
 * Loads the extracted puppeteer-extra-plugin-stealth evasion bundle
 * and injects it into the webview's main world via a <script> element.
 * Also adds iframe interception to ensure chrome object is present in dynamic iframes.
 * 
 * The bundle is generated by: node scripts/extract-stealth.cjs
 * Source: puppeteer-extra-plugin-stealth (13 evasion modules)
 * 
 * IMPORTANT: With contextIsolation: true, preload scripts run in an isolated
 * JavaScript context. We must inject into the MAIN WORLD via <script> element
 * so the evasions affect what the page sees.
 * 
 * NOTE: The stealth code is inlined by esbuild at build time (from stealthBundle.cjs)
 * because sandbox: true means fs/path are NOT available at runtime.
 */

const { stealthCode } = require('./stealthBundle.cjs');

// Additional script to:
// 1. Override navigator.userAgentData to include "Google Chrome" brand
// 2. Intercept dynamic iframe creation and inject chrome object
const iframeInterceptScript = `
(function() {
    'use strict';

    // ─── navigator.userAgentData override ────────────────────────────
    // Electron only reports "Chromium" brand, not "Google Chrome"
    // This is a major detection vector — must include Google Chrome brand
    //
    // IMPORTANT: For Google login pages (accounts.google.com), we do NOT
    // claim "Google Chrome" because Google can verify this cryptographically.
    // Learned from v-box-latest (Wexond) which removes Chrome component
    // entirely for Google login URLs.
    try {
        const platform = navigator.platform || 'Win32';
        const isMobile = false;
        const platformName = platform.startsWith('Mac') ? 'macOS' :
                            platform.startsWith('Linux') ? 'Linux' : 'Windows';

        // Check if we're on a Google login page
        const isGoogleLogin = /^https:\\/\\/accounts\\.google\\.com(\\/|$)/.test(window.location.href);

        // For Google login: only claim "Chromium" (not "Google Chrome")
        // For all other sites: claim full "Google Chrome" brand
        const brands = isGoogleLogin ? [
            { brand: 'Chromium', version: '132' },
            { brand: 'Not_A Brand', version: '24' }
        ] : [
            { brand: 'Chromium', version: '132' },
            { brand: 'Not_A Brand', version: '24' },
            { brand: 'Google Chrome', version: '132' }
        ];

        const fullVersionList = isGoogleLogin ? [
            { brand: 'Chromium', version: '132.0.6834.210' },
            { brand: 'Not_A Brand', version: '24.0.0.0' }
        ] : [
            { brand: 'Chromium', version: '132.0.6834.210' },
            { brand: 'Not_A Brand', version: '24.0.0.0' },
            { brand: 'Google Chrome', version: '132.0.6834.210' }
        ];

        const uaData = {
            brands: Object.freeze(brands),
            mobile: isMobile,
            platform: platformName,
            getHighEntropyValues: function(hints) {
                return Promise.resolve({
                    brands: Object.freeze(brands),
                    fullVersionList: Object.freeze(fullVersionList),
                    mobile: isMobile,
                    model: '',
                    platform: platformName,
                    platformVersion: platformName === 'Windows' ? '15.0.0' :
                                    platformName === 'macOS' ? '15.5.0' : '',
                    uaFullVersion: '132.0.6834.210',
                    architecture: 'x86',
                    bitness: '64',
                    wow64: false
                });
            },
            toJSON: function() {
                return {
                    brands: this.brands,
                    mobile: this.mobile,
                    platform: this.platform
                };
            }
        };

        // Define on Navigator.prototype (not navigator instance) so
        // Object.getOwnPropertyNames(navigator) returns empty array
        // (matching real Chrome behavior where props are on prototype)
        Object.defineProperty(Navigator.prototype, 'userAgentData', {
            get: function() { return uaData; },
            configurable: true,
            enumerable: true
        });
    } catch(_) {}

    // Ensure chrome object exists on main window
    if (!window.chrome) {
        window.chrome = {};
    }

    // Store reference to the chrome object we want to propagate
    const chromeObj = window.chrome;

    // ─── Method 1: Patch contentWindow getter ────────────────────────
    try {
        const origDescriptor = Object.getOwnPropertyDescriptor(
            HTMLIFrameElement.prototype, 'contentWindow'
        );
        
        if (origDescriptor && origDescriptor.get) {
            Object.defineProperty(HTMLIFrameElement.prototype, 'contentWindow', {
                get: function() {
                    const win = origDescriptor.get.call(this);
                    if (win) {
                        try {
                            // Only patch if chrome is missing or incomplete
                            if (!win.chrome) {
                                win.chrome = chromeObj;
                            }
                        } catch(e) {
                            // Cross-origin iframe — can't access, that's normal
                        }
                    }
                    return win;
                },
                configurable: true,
                enumerable: true
            });
        }
    } catch(_) {}

    // ─── Method 2: MutationObserver for dynamic iframes ──────────────
    try {
        const injectChrome = function(iframe) {
            try {
                if (iframe.contentWindow && !iframe.contentWindow.chrome) {
                    iframe.contentWindow.chrome = chromeObj;
                }
            } catch(e) {
                // Cross-origin — can't access
            }
        };

        // Watch for dynamically added iframes
        const observer = new MutationObserver(function(mutations) {
            for (const mutation of mutations) {
                for (const node of mutation.addedNodes) {
                    if (node.tagName === 'IFRAME') {
                        injectChrome(node);
                    }
                    // Check children too
                    if (node.querySelectorAll) {
                        const iframes = node.querySelectorAll('iframe');
                        for (const iframe of iframes) {
                            injectChrome(iframe);
                        }
                    }
                }
            }
        });

        // Start observing as soon as document is available
        const target = document.documentElement || document.body || document;
        observer.observe(target, {
            childList: true,
            subtree: true
        });

        // Also patch existing iframes
        document.querySelectorAll('iframe').forEach(injectChrome);

        // Patch createElement to catch iframes created but not yet in DOM
        const origCreateElement = document.createElement.bind(document);
        document.createElement = function(tagName, options) {
            const element = origCreateElement(tagName, options);
            if (tagName.toLowerCase() === 'iframe') {
                // Try to inject when iframe loads
                element.addEventListener('load', function() {
                    injectChrome(element);
                });
                // Also try immediately in case it's already loaded
                setTimeout(function() { injectChrome(element); }, 0);
            }
            return element;
        };
    } catch(_) {}
})();
`;

function initStealthEvasion() {
    if (!stealthCode) {
        console.warn('[Stealth] No evasion code available');
        return;
    }

    // Combine the main stealth bundle with iframe interception
    const fullScript = stealthCode + '\n' + iframeInterceptScript;

    // Inject into main world via script element
    // This must run BEFORE any page scripts to be effective
    try {
        const script = document.createElement('script');
        script.textContent = fullScript;
        
        // Insert as early as possible
        const target = document.documentElement || document.head || document.body || document;
        if (target.firstChild) {
            target.insertBefore(script, target.firstChild);
        } else {
            target.appendChild(script);
        }
        
        // Remove the script element after execution (clean up evidence)
        script.remove();
        
        console.log('[Stealth] Evasion bundle + iframe intercept injected into main world');
    } catch (_) {
        // Fallback: if DOM isn't ready yet, try on DOMContentLoaded
        try {
            document.addEventListener('DOMContentLoaded', function() {
                try {
                    const script = document.createElement('script');
                    script.textContent = fullScript;
                    (document.head || document.documentElement).prepend(script);
                    script.remove();
                    console.log('[Stealth] Evasion bundle injected (DOMContentLoaded)');
                } catch (_) {}
            }, { once: true });
        } catch (_) {}
    }
}

module.exports = { init: initStealthEvasion };
