const { app } = require('electron');
const PptxGenJS = require('pptxgenjs');
const PizZip = require('pizzip');
const Docxtemplater = require('docxtemplater');
const fs = require('fs');
const path = require('path');

const TEMPLATES_DIR = path.join(app.getAppPath(), 'ppt-templates');

class PowerPointController {
    // Generate PowerPoint from scratch with slides
    static async generate(event, pptData) {
        try {
            console.log('� Generating PowerPoint:', pptData.filename);
            
            const pptx = new PptxGenJS();
            
            pptx.author = pptData.author || 'VBox Script';
            pptx.title = pptData.title || 'VBox Report';
            pptx.subject = 'Generated by VBox Script Injector';
            
            if (pptData.template) {
                PowerPointController.applyTemplate(pptx, pptData.template);
            }
            
            for (const slideData of pptData.slides) {
                const slide = pptx.addSlide();
                
                if (pptData.template && pptData.template.background) {
                    slide.background = pptData.template.background;
                }
                
                if (slideData.type === 'title') {
                    const titleStyle = pptData.template?.titleStyle || {
                        fontSize: 44,
                        bold: true,
                        color: '363636'
                    };
                    
                    slide.addText(slideData.title, {
                        x: 0.5,
                        y: 1.5,
                        w: 9,
                        h: 1.5,
                        align: 'center',
                        ...titleStyle
                    });
                    
                    if (slideData.subtitle) {
                        const subtitleStyle = pptData.template?.subtitleStyle || {
                            fontSize: 24,
                            color: '666666'
                        };
                        
                        slide.addText(slideData.subtitle, {
                            x: 0.5,
                            y: 3.5,
                            w: 9,
                            h: 0.75,
                            align: 'center',
                            ...subtitleStyle
                        });
                    }
                } else if (slideData.type === 'content') {
                    if (slideData.title) {
                        const headerStyle = pptData.template?.headerStyle || {
                            fontSize: 32,
                            bold: true,
                            color: '363636'
                        };
                        
                        slide.addText(slideData.title, {
                            x: 0.5,
                            y: 0.5,
                            w: 9,
                            h: 0.75,
                            ...headerStyle
                        });
                    }
                    
                    let yPos = 1.5;
                    if (slideData.content && Array.isArray(slideData.content)) {
                        for (const item of slideData.content) {
                            if (item.type === 'text') {
                                const options = {
                                    x: item.options?.x || 0.5,
                                    y: item.options?.y || yPos,
                                    w: item.options?.w || 9,
                                    h: item.options?.h || 0.5,
                                    fontSize: item.options?.fontSize || 18,
                                    color: item.options?.color || '363636',
                                    align: item.options?.align || 'left',
                                    ...item.options
                                };
                                slide.addText(item.text, options);
                                yPos += options.h + 0.2;
                            } else if (item.type === 'image') {
                                const options = {
                                    x: item.options?.x || 1,
                                    y: item.options?.y || yPos,
                                    w: item.options?.w || 8,
                                    h: item.options?.h || 4,
                                    ...item.options
                                };
                                
                                if (item.path) {
                                    // Read file and convert to base64 for better compatibility
                                    try {
                                        const imageBuffer = fs.readFileSync(item.path);
                                        const base64Image = imageBuffer.toString('base64');
                                        const ext = path.extname(item.path).toLowerCase();
                                        const mimeType = ext === '.png' ? 'image/png' : 'image/jpeg';
                                        const dataURL = `data:${mimeType};base64,${base64Image}`;
                                        
                                        slide.addImage({
                                            data: dataURL,
                                            ...options
                                        });
                                    } catch (err) {
                                        console.error('Failed to read image file:', err);
                                        // Fallback to path
                                        slide.addImage({
                                            path: item.path,
                                            ...options
                                        });
                                    }
                                } else if (item.data) {
                                    slide.addImage({
                                        data: item.data,
                                        ...options
                                    });
                                }
                                yPos += options.h + 0.2;
                            } else if (item.type === 'table') {
                                const options = {
                                    x: item.options?.x || 0.5,
                                    y: item.options?.y || yPos,
                                    w: item.options?.w || 9,
                                    fontSize: item.options?.fontSize || 14,
                                    border: item.options?.border !== false ? { pt: 1, color: 'CFCFCF' } : null,
                                    ...item.options
                                };
                                slide.addTable(item.rows, options);
                                yPos += 3;
                            } else if (item.type === 'chart') {
                                const options = {
                                    x: item.options?.x || 1,
                                    y: item.options?.y || yPos,
                                    w: item.options?.w || 8,
                                    h: item.options?.h || 4,
                                    ...item.options
                                };
                                slide.addChart(item.chartType, item.data, options);
                                yPos += options.h + 0.2;
                            }
                        }
                    }
                }
            }
            
            const downloadsPath = app.getPath('downloads');
            const filename = pptData.filename || 'vbox-report.pptx';
            const filePath = path.join(downloadsPath, filename);
            
            await pptx.writeFile({ fileName: filePath });
            
            console.log('✅ PowerPoint saved:', filePath);
            
            const stats = fs.statSync(filePath);
            
            return {
                success: true,
                path: filePath,
                filename: filename,
                size: stats.size
            };
        } catch (error) {
            console.error('❌ Failed to generate PowerPoint:', error);
            return {
                success: false,
                error: error.message
            };
        }
    }

    // Process template with variable replacement
    static async processTemplate(event, { templateName, variables, outputFilename }) {
        try {
            console.log('📄 Processing template:', templateName);
            console.log('📝 Variables:', variables);
            
            const templatePath = path.join(TEMPLATES_DIR, templateName);
            
            if (!fs.existsSync(templatePath)) {
                throw new Error(`Template not found: ${templateName}`);
            }
            
            const content = fs.readFileSync(templatePath, 'binary');
            const zip = new PizZip(content);
            
            const doc = new Docxtemplater(zip, {
                paragraphLoop: true,
                linebreaks: true,
                delimiters: {
                    start: '{{',
                    end: '}}'
                }
            });
            
            doc.setData(variables);
            
            try {
                doc.render();
            } catch (error) {
                console.error('❌ Template render error:', error);
                throw new Error(`Failed to render template: ${error.message}`);
            }
            
            const buf = doc.getZip().generate({
                type: 'nodebuffer',
                compression: 'DEFLATE'
            });
            
            const downloadsPath = app.getPath('downloads');
            const outputPath = path.join(downloadsPath, outputFilename);
            
            fs.writeFileSync(outputPath, buf);
            
            console.log('✅ Template processed:', outputPath);
            
            const stats = fs.statSync(outputPath);
            
            return {
                success: true,
                path: outputPath,
                filename: outputFilename,
                size: stats.size
            };
            
        } catch (error) {
            console.error('❌ Failed to process template:', error);
            return {
                success: false,
                error: error.message
            };
        }
    }

    // List available templates
    static async listTemplates(event) {
        try {
            if (!fs.existsSync(TEMPLATES_DIR)) {
                fs.mkdirSync(TEMPLATES_DIR, { recursive: true });
                return { success: true, templates: [] };
            }
            
            const files = fs.readdirSync(TEMPLATES_DIR);
            const templates = files
                .filter(file => file.endsWith('.pptx'))
                .map(file => ({
                    name: file,
                    path: path.join(TEMPLATES_DIR, file),
                    size: fs.statSync(path.join(TEMPLATES_DIR, file)).size
                }));
            
            return { success: true, templates };
        } catch (error) {
            console.error('❌ Failed to list templates:', error);
            return { success: true, templates: [] };
        }
    }

    // Get templates directory path
    static async getTemplatesDir(event) {
        return { success: true, path: TEMPLATES_DIR };
    }

    // Apply template settings to presentation
    static applyTemplate(pptx, template) {
        if (template.layout) {
            pptx.layout = template.layout;
        }
    }
}

module.exports = { PowerPointController };
